// Generated by CoffeeScript 1.3.3
(function() {
  var MyPlayer;

  MyPlayer = (function() {

    function MyPlayer() {}

    MyPlayer.prototype.id = -1;

    MyPlayer.prototype.name = null;

    MyPlayer.prototype.betAmount = 0;

    MyPlayer.prototype.isLoggedIn = function() {
      if (id !== -1) {
        return true;
      }
    };

    MyPlayer.prototype.onLogin = function(playerId, name) {
      console.log("COFFEEE!!!! Logging in, playerId = " + playerId + " name = " + name);
      this.id = playerId;
      return this.name = name;
    };

    MyPlayer.prototype.clear = function() {
      var id, name;
      id = -1;
      return name = "";
    };

    return MyPlayer;

  })();

  window.Poker.MyPlayer = new MyPlayer();

}).call(this);
