// Generated by CoffeeScript 1.3.3
(function() {
  var Player;

  Player = (function() {

    Player.prototype.balance = 0;

    Player.prototype.tableStatus = null;

    Player.prototype.lastActionType = null;

    Player.prototype.cards = [];

    function Player(id, name) {
      this.id = id;
      this.name = name;
      this.tableStatus = Poker.PlayerTableStatus.SITTING_IN;
    }

    /*
      Adds a card to the player
      @param card to add
    */


    Player.prototype.addCard = function(card) {
      return this.cards.push(card);
    };

    return Player;

  })();

  window.Poker.Player = Player;

}).call(this);
