package com.cubeia.games.poker.util;

/**
 * Composite key class generated by player id and table id.
 *
 * @author Fredrik Johansson, Cubeia Ltd
 */
public class TablePlayerKey {
    public final int pid;
    public final int tableId;
    
    public TablePlayerKey(int tableId, int pid) {
        this.pid = pid;
        this.tableId = tableId;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + pid;
        result = prime * result + tableId;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TablePlayerKey other = (TablePlayerKey) obj;
        if (pid != other.pid)
            return false;
        if (tableId != other.tableId)
            return false;
        return true;
    }
}
